services:
  obsidian-chat:
    build: .
    container_name: obsidian_ai_tool
    ports:
      - "8005:8000"
    volumes:
      # Пробрасываем твое хранилище Obsidian, чтобы RAG его видел
      - /home/matafix/obsidian_knowlage/md_store:/app/vault:ro
      # Пробрасываем базу FAISS, чтобы она не терялась при перезагрузке
      - /home/matafix/obsidian_knowlage/faiss:/app/vector_db
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - VAULT_PATH=/app/vault
    restart: always